---
kind: pipeline
type: docker
name: cran-latest

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: "Check package: R 4.1"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"', dependencies = TRUE)'
  - R -s -e 'devtools::load_all(); sessioninfo::session_info()'
  - R -s -e 'devtools::check(env_vars = c("PMF_SKIP_VDIFFR" = "true", "NOT_CRAN" = "true"))'
  environment:
    USER: drone
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: pmforest-release

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Build package
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - git config --global user.email drone@metrumrg.com
  - git config --global user.name Drony
  - git fetch --tags
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"', dependencies = TRUE)'
  - R -s -e 'pkgpub::create_tagged_repo(.dir = '"'"'/ephemeral'"'"')'
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: ${DRONE_TAG}"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/${DRONE_TAG}
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: latest_tag"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/latest_tag
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
  - tag

depends_on:
- cran-latest

---
kind: pipeline
type: docker
name: pmforest-release-mrgval

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mrgval:next
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Generate validation docs
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mrgval:next
  commands:
  - git config --global user.email drone@metrumrg.com
  - git config --global user.name Drony
  - git fetch --tags
  - |
    /mrgval/create-validation-docs.sh \
      --results-dir /ephemeral/${DRONE_BUILD_NUMBER}/val/test-results \
      --docs-dir /ephemeral/${DRONE_BUILD_NUMBER}/val/docs \
      -s inst/validation/pmforest-stories.yaml
  environment:
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

# TODO:
# - name: "Publish validation docs: ${DRONE_TAG}"
# ... and probably switch target to use TAG.
- name: "Publish validation docs"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mrg-validation
    region: us-west-2
    source: /ephemeral/${DRONE_BUILD_NUMBER}/val/**/*
    strip_prefix: /ephemeral/${DRONE_BUILD_NUMBER}/val
    target: /mrgval-scratch/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

# TODO: switch to tag
trigger:
  event:
  - push

depends_on:
- cran-latest
